# Generated by Django 5.0.4 on 2024-04-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_test_testitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testitem',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='word',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestItem',
        ),
    ]
